// app/links/page.tsx
import type { SocialLink } from "@/lib/types";

const links: SocialLink[] = [
  {
    title: "Twitter (X)",
    text: "My Twitter (X) account.",
    link: "https://x.com/_Hunter_T_",
    color: "#1DA1F2",
  },
  {
    title: "GitHub",
    text: "My GitHub account.",
    link: "https://github.com/StrangeRanger",
    color: "#ffffff",
  },
  {
    title: "SoundCloud",
    text: "My SoundCloud account.",
    link: "https://soundcloud.com/SubDubZero",
    color: "#FF5500",
  },
];

export default function LinksPage() {
  return (
    <div>
      <section className="section-card">
        <h1>My Links</h1>
        <p>Connect with me on various social media platforms and explore my work.</p>
      </section>

      <section className="section-card">
        <div className="card-grid">
          {links.map((item) => (
            <article key={item.title} className="card-link" style={{ borderColor: item.color }}>
              <a href={item.link} target="_blank" rel="noopener noreferrer">
                <h3>{item.title}</h3>
                <p>{item.text}</p>
              </a>
            </article>
          ))}
        </div>
      </section>
    </div>
  );
}

// app/pages/links.vue
<script setup lang="ts">
interface SocialLink {
  title: string;
  text: string;
  link: string;
  icon: string;
  color: string;
}

const array: SocialLink[] = [
  {
    title: "Twitter (X)",
    text: "My Twitter (X) account.",
    link: "https://x.com/_Hunter_T_",
    icon: "mdi-twitter",
    color: "#1DA1F2",
  },
  {
    title: "GitHub",
    text: "My GitHub account.",
    link: "https://github.com/StrangeRanger",
    icon: "mdi-github",
    color: "#ffffff",
  },
  {
    title: "SoundCloud",
    text: "My SoundCloud account.",
    link: "https://soundcloud.com/SubDubZero",
    icon: "mdi-soundcloud",
    color: "#FF5500",
  },
];
</script>

<template>
  <v-container class="button-links">
    <v-sheet class="rounded pb-6">
      <h1 class="text-h4 mb-5 text-center">My Links</h1>
      <p class="text-body-1 text-center mb-6">
        Connect with me on various social media platforms and explore my work.
      </p>
    </v-sheet>

    <v-sheet class="rounded pb-6 mt-6">
      <v-row>
        <v-col v-for="item in array" :key="item.title" cols="12" sm="6" md="4">
          <v-card
            class="card-button"
            :href="item.link"
            rel="noopener noreferrer"
            target="_blank"
            elevation="6"
            variant="outlined"
            :color="item.color"
          >
            <v-card-title
              class="text-center d-flex align-center justify-center ga-2"
            >
              <v-icon :icon="item.icon" />
              {{ item.title }}
            </v-card-title>
            <v-card-item>
              <v-card-text class="text-body-1 text-center">
                {{ item.text }}
              </v-card-text>
            </v-card-item>
          </v-card>
        </v-col>
      </v-row>
    </v-sheet>
  </v-container>
</template>

<style scoped>
.card-button {
  transition: transform 0.2s ease-in-out;
}

.card-button:hover {
  transform: translateY(-2px);
}
</style>
