// pages/links.vue
<script setup lang="ts">
const array = [
  {
    title: 'Twitter',
    text: 'My Twitter account.',
    link: 'https://twitter.com/_Hunter_T_',
    icon: 'mdi-twitter',
    color: '#1DA1F2'
  },
  {
    title: 'SoundCloud',
    text: 'My SoundCloud account.',
    link: 'https://soundcloud.com/SubDubZero',
    icon: 'mdi-soundcloud',
    color: '#FF5500'
  },
  {
    title: 'GitHub',
    text: 'My GitHub account.',
    link: 'https://github.com/StrangeRanger',
    icon: 'mdi-github',
    color: '#ffffff'
  }
]
</script>

<template>
  <div>
    <h1 class="text-h4">My Links</h1>
    <br >
    <v-container class="button-links">
      <v-row>
        <v-col v-for="item in array" :key="item.title" cols="12" sm="6" md="4">
          <v-card
            class="card-button"
            :href="item.link"
            target="_blank"
            elevation="6"
            variant="outlined"
            :color="item.color"
          >
            <v-card-title class="text-center">
              <v-icon :icon="item.icon" />
              {{ item.title }}
            </v-card-title>
            <v-card-item>
              <v-card-text class="text-body-1 text-left">
                {{ item.text }}
              </v-card-text>
            </v-card-item>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </div>
</template>

<style scoped>
v-img {
  text-align: center;
}
</style>

// app/links/page.tsx
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import Card from "@mui/material/Card";
import Button from "@mui/material/Button";
import CardContent from "@mui/material/CardContent";

export default function MyLinks() {
  interface SocialLink {
    title: string;
    body: string;
    link: string;
    icon: string;
    color: string;
  }

  const socialLinks: SocialLink[] = [
    {
      title: "Twitter (X)",
      body: "My Twitter (X) account.",
      link: "https://x.com/_Hunter_T_",
      icon: "mdi-twitter",
      color: "#1DA1F2",
    },
    {
      title: "GitHub",
      body: "My GitHub account.",
      link: "https://github.com/StrangeRanger",
      icon: "mdi-github",
      color: "#ffffff",
    },
    {
      title: "SoundCloud",
      body: "My SoundCloud account.",
      link: "https://soundcloud.com/SubDubZero",
      icon: "mdi-soundcloud",
      color: "#FF5500",
    },
  ];

  return (
    <Box>
      <Typography variant="h3" component="h1" align="center" sx={{ mb: 3 }}>
        My Links
      </Typography>
      <Typography variant="body1" sx={{ my: 4, textAlign: "center" }}>
        Connect with me on various social media platforms and explore my work.
      </Typography>
      <Grid container spacing={3}>
        {socialLinks.map((item: SocialLink) => (
          <Grid key={item.title} size={{ xs: 12, sm: 6, lg: 4 }}>
            <Card sx={{ color: item.color, borderColor: item.color }}>
              <Button
                href={item.link}
                sx={{
                  display: "block",
                  textAlign: "left",
                  color: "inherit",
                  p: 0,
                  borderRadius: 0,
                }}
              >
                <CardContent>
                  <Typography variant="h6" component="h3" sx={{ mb: 2 }}>
                    {item.title}
                  </Typography>
                  <Typography variant="body2">{item.body}</Typography>
                </CardContent>
              </Button>
            </Card>
          </Grid>
        ))}
      </Grid>
    </Box>
  );
}
